### ISSUE TITLE
to use redux or not to use, that is the question

### ISSUE THREAD

**Issue by hugelive** [hugelive/hugelive.com#57]
I need to do some research on redux first... What do you guys think?

**Comment by hugeliveux** [comment]
IMHO, if not necessary, Redux will still save a lot of repetitive works, such as passing props through layers who don't really need them but only for their children, or children's children...

Also, a single source of truth is handy when we want the app to behave consistently.

Let's look into the draw-backs more. There should be alternatives to achieve global state management.
