### ISSUE TITLE
Network Error presents

### ISSUE THREAD

**Issue by hugeliveux** [hugelive/hugelive.com#59]
#### Issue description

The app shows "Network Error" where the resource should be loaded.

#### Steps to reproduce the issue

1. Checkout branch "npm-package-update" locally and pull from origin
2. `npm i`
3. `npm i mongodb-client-encryption` (this step was skipped in the first try, does not change the result)
4. `npm run build`
5. `npm run start`
6. Browse http://localhost:3000

#### What's the expected result?

- The resource should be loaded after spinning a while, and the app should function as expected

#### What's the actual result?

- After the spinner, only a red string "Network Error" presented between head and foot

#### Additional details / screenshot

<img width="146" alt="image" src="https://user-images.githubusercontent.com/65123894/82422272-17b77800-9a37-11ea-9aca-353bc0f359d8.png">

**Comment by hugelive** [comment]
I forgot to send you guys mongo connection string... My bad.
And "Network Error" is the expected result without connection string. Nothing to worry about. Closed this bug for now.
